version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: fest_postgres
    restart: always
    environment:
      POSTGRES_USER: fest_admin
      POSTGRES_PASSWORD: fest_password
      POSTGRES_DB: fest_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
