version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: fest_admin
      POSTGRES_PASSWORD: fest_password
      POSTGRES_DB: fest_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db

volumes:
  pgdata: